name: Operion CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest


    services:
      mysql:
        image: mysql:8

        env:
          MYSQL_DATABASE: operion
          MYSQL_USER: admin
          MYSQL_PASSWORD: 123123
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Make Maven Wrapper executable
        run: chmod +x mvnw


      - name: Run tests
        run: ./mvnw test
        env:
          DB_URL: jdbc:mysql://localhost:3306/operion
          DB_USERNAME: admin
          DB_PASSWORD: 123123
          JWT_SECRET: ZHVtbXktc2VjcmV0LWtleS1mb3ItdGVzdGluZy0zMjIzMjMyMzIzMjMyMzI=


      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/operion-api:latest .
          docker push ghcr.io/${{ github.repository_owner }}/operion-api:latest